### PR TITLE
Fix midi2wav empty note error

### PR DESCRIPTION
**Pull request by josefleventon**
#### Fix midi2wav empty note error
After working with this package for a while, I've come across an issue that I find quite frankly disturbing. When SynthJS is faced with the conversion of a MIDI file with empty spaces to WAV, it will create the following error:

```js
let note = map.get(semitone).pop();

TypeError: Cannot read property 'pop' of undefined
    at Object.midiToWav (/*/node_modules/synth-js/src/midi2wav.js:131:41)
```

This pull request implements a simple check that verifies if the `map.get(semitone)` call returns anything, and if not, sets the note to a 0 object, which looks like this:
```js
[{ offset: 0, velocity: 0 }]
```

This eliminates the error, and works just fine when converting MIDI to WAV.
Here's an example of a file generated with this new method:
https://cdn.filestackcontent.com/0kWizDlRrqN3Mdnl7A2H

### CODE REVIEW

**Comment by josefleventon** [comment]
**Starting line 130**
Removed:
```js
let note = map.get(semitone).pop();
```
Added:
```js
// create note
let note;

if (!map.get(semitone)) note = [{offset:0, velocity: 0}] // if no semitone, set empty note
else note = map.get(semitone).pop(); // set note to semitone minus last
```

**Comment by josefleventon** [comment]
Please note that the first commit applied the Prettier code formatter's formatting rules, therefore I rolled it back in a second commit, which follows the design rules that you've seemed to be implementing in your code.

**Comment by patrickroberts** [comment]
@josefleventon thanks for your interest in this package! I appreciate the pull request but there's a couple issues with what you've written. `note` should not be an array here, it should be the object itself (note the usage [here](https://github.com/patrickroberts/synth-js/pull/2/files#diff-65c41832a6474b8da63b5675c85c2713R139-R141)), and your pull request should only need to call `map.get(semitone)` once.

Here's an implementation I would believe to be correct based on the issue you're trying to resolve.

```js
const notes = map.get(semitone);
const note = notes ? notes.pop() : { offset: 0, velocity: 0 };
```

Would you mind verifying that the suggestion above works as you'd like and make the necessary changes to your pull request? If you include a version bump to the patch in the `package.json` I'll merge it and update the package on npm as well.

Thanks.

**Comment by josefleventon** [comment]
Thank you for responding! I'll make sure to check whenever I get back to my computer.

**Comment by josefleventon** [comment]
@patrickroberts Works well! I've committed the changes.

**Comment by patrickroberts** [comment]
Thanks again for your contribution. I've rerun the gulp task and published it on [npm](https://www.npmjs.com/package/synth-js/v/0.1.2).

**Pull request merged**
